apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
- ../../base
- serviceaccount.yaml

images:
  - name: public.ecr.aws/eks/aws-load-balancer-controller
    newName: 823091238322.dkr.ecr.eu-central-1.amazonaws.com/ecr-public/eks/aws-load-balancer-controller

#    newName: 466323560378.dkr.ecr.eu-central-1.amazonaws.com/ecr-public/eks/aws-load-balancer-controller

