apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  source:
    path: manifests/argocd/overlays/prd
    repoURL: https://github.com/michielvha/aws-argocd
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: infra
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  source:
    path: manifests/kyverno-app/overlays/aws
    repoURL: https://github.com/michielvha/aws-argocd
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - PruneLast=true
      - ServerSideApply=true
---
#apiVersion: argoproj.io/v1alpha1
#kind: Application
#metadata:
#  name: devteam-infra
#  namespace: infra
#  annotations:
#    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
#  finalizers:
#  - resources-finalizer.argocd.argoproj.io
#spec:
#  destination:
#    namespace: infra
#    name: in-cluster
#  project: devteam-infra
#  source:
#    path: manifests/infra-app/overlays/prd
#    repoURL: https://github.com/michielvha/aws-argocd
#    targetRevision: main
#  syncPolicy:
#    automated:
#      selfHeal: true
#      prune: true
#    syncOptions:
#      - PruneLast=true
#      - ServerSideApply=true