apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.14.0/manifests/ha/install.yaml
  - rbac.yaml
  - app.yaml
  - namespace.yaml
  - ingress.yaml

images:
  - name: quay.io/argoproj/argocd
    newName: 833935676990.dkr.ecr.eu-west-1.amazonaws.com/quay/argoproj/argocd

  - name: public.ecr.aws/docker/library/redis
    newName: 833935676990.dkr.ecr.eu-west-1.amazonaws.com/docker/library/redis

  - name: public.ecr.aws/docker/library/haproxy
    newName: 833935676990.dkr.ecr.eu-west-1.amazonaws.com/docker/library/haproxy

  - name: ghcr.io/dexidp/dex
    newName: 833935676990.dkr.ecr.eu-west-1.amazonaws.com/github/dexidp/dex


patches:
  - target:
      kind: ConfigMap
      name: argocd-cmd-params-cm
    patch: |-
      - op: add
        path: /data/server.insecure
        value: "true"