apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../base

images:
  - name: nicolaka/netshoot
    newName: 823091238322.dkr.ecr.eu-central-1.amazonaws.com/docker/nicolaka/netshoot