apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: reloader

resources:
  - https://raw.githubusercontent.com/stakater/Reloader/v1.4.5/deployments/kubernetes/reloader.yaml

#patches:
#  - target:
#      kind: Deployment
#    patch: |-
#      - op: add
#        path: /spec/template/spec/imagePullSecrets
#        value: [{ name: jfrog-artifactory-secret }]