apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kyverno-system

resources:
#  - ../../base
  - policy.yaml
  - namespace.yaml

helmGlobals:
  chartHome: helm

helmCharts:
- name: kyverno
  namespace: kyverno-system
  valuesFile: values.yaml
  releaseName: kyverno
  includeCRDs: true
#  version: 3.4.4

#  repo: https://kyverno.github.io/kyverno/
#  version: 3.3.1



#images:
#  - name: ghcr.io/kyverno/kyvernopre
#    newName: 833935676990.dkr.ecr.eu-west-1.amazonaws.com/ghcr.io/kyverno/kyvernopre
#  - name: ghcr.io/kyverno/kyverno
#    newName: 833935676990.dkr.ecr.eu-west-1.amazonaws.com/ghcr.io/kyverno/kyverno
#  - name: ghcr.io/kyverno/background-controller
#    newName: 833935676990.dkr.ecr.eu-west-1.amazonaws.com/ghcr.io/kyverno/background-controller
#  - name: ghcr.io/kyverno/cleanup-controller
#    newName: 833935676990.dkr.ecr.eu-west-1.amazonaws.com/ghcr.io/kyverno/cleanup-controller
#  - name: ghcr.io/kyverno/reports-controller
#    newName: 833935676990.dkr.ecr.eu-west-1.amazonaws.com/ghcr.io/kyverno/reports-controller