apiVersion: v1
kind: Pod
metadata:
  name: netshoot
  namespace: default
spec:
  containers:
  - name: netshoot
    image: nicolaka/netshoot:v0.14
    command: ["/bin/bash"]
    args: ["-c", "while true; do ping localhost; sleep 60;done"]