apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: kargo-demo
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: kargo-demo-repo
  namespace: kargo-demo
  labels:
    kargo.akuity.io/cred-type: git
stringData:
  repoURL: https://github.com/kratarget/octopus_oneretail_deploy
  # username: ${GITHUB_USERNAME}
  # password: ${GITHUB_PAT}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-demo
  namespace: kargo-demo
spec:
  subscriptions:
  - image:
      repoURL: ghcr.io/kroonprins/nginx
      semverConstraint: ^1.26.0
      discoveryLimit: 5
  - git:
      repoURL: https://github.com/kratarget/octopus_oneretail_deploy
      branch: main
      strictSemvers: false
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: test
  namespace: kargo-demo
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      direct: true
  promotionTemplate:
    spec:
      vars:
      - name: gitopsRepo
        value: ${GITOPS_REPO_URL}
      - name: imageRepo
        value: ghcr.io/kroonprins/nginx
      - name: srcPath
        value: ./src
      - name: outPath
        value: ./out
      steps:
      - uses: git-clone
        config:
          repoURL: \${{ vars.gitopsRepo }}
          checkout:
          - fromFreight: true
            path: \${{ vars.srcPath }}
          - branch: stage/\${{ ctx.stage }}
            create: true
            path: \${{ vars.outPath }}
      - uses: git-clear
        config:
          path: \${{ vars.outPath }}
      # - uses: kustomize-set-image
      #   as: update-image
      #   config:
      #     path: \${{ vars.srcPath }}/base
      #     images:
      #     - image: \${{ vars.imageRepo }}
      #       tag: \${{ imageFrom(vars.imageRepo).Tag }}
      - uses: kustomize-build
        config:
          path: \${{ vars.srcPath }}/stages/\${{ ctx.stage }}
          outPath: \${{ vars.outPath }}/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: \${{ vars.outPath }}
          messageFromSteps:
          - update-image
      - uses: git-push
        config:
          path: \${{ vars.outPath }}
      - uses: argocd-update
        config:
          apps:
          - name: kargo-demo-\${{ ctx.stage }}
            sources:
            - repoURL: \${{ vars.gitopsRepo }}
              desiredRevision: \${{ outputs.commit.commit }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: uat
  namespace: kargo-demo
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - test
  promotionTemplate:
    spec:
      vars:
      - name: gitopsRepo
        value: ${GITOPS_REPO_URL}
      - name: imageRepo
        value: ghcr.io/kroonprins/nginx
      - name: srcPath
        value: ./src
      - name: outPath
        value: ./out
      steps:
      - uses: git-clone
        config:
          repoURL: \${{ vars.gitopsRepo }}
          checkout:
          - fromFreight: true
            path: \${{ vars.srcPath }}
          - branch: stage/\${{ ctx.stage }}
            create: true
            path: \${{ vars.outPath }}
      - uses: git-clear
        config:
          path: \${{ vars.outPath }}
      # - uses: kustomize-set-image
      #   as: update-image
      #   config:
      #     path: \${{ vars.srcPath }}/base
      #     images:
      #     - image: \${{ vars.imageRepo }}
      #       tag: \${{ imageFrom(vars.imageRepo).Tag }}
      - uses: kustomize-build
        config:
          path: \${{ vars.srcPath }}/stages/\${{ ctx.stage }}
          outPath: \${{ vars.outPath }}/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: \${{ vars.outPath }}
          messageFromSteps:
          - update-image
      - uses: git-push
        config:
          path: \${{ vars.outPath }}
      - uses: argocd-update
        config:
          apps:
          - name: kargo-demo-\${{ ctx.stage }}
            sources:
            - repoURL: \${{ vars.gitopsRepo }}
              desiredRevision: \${{ outputs.commit.commit }}
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: kargo-demo
spec:
  requestedFreight:
  - origin:
      kind: Warehouse
      name: kargo-demo
    sources:
      stages:
      - uat
  promotionTemplate:
    spec:
      vars:
      - name: gitopsRepo
        value: ${GITOPS_REPO_URL}
      - name: imageRepo
        value: ghcr.io/kroonprins/nginx
      - name: srcPath
        value: ./src
      - name: outPath
        value: ./out
      steps:
      - uses: git-clone
        config:
          repoURL: \${{ vars.gitopsRepo }}
          checkout:
          - fromFreight: true
            path: \${{ vars.srcPath }}
          - branch: stage/\${{ ctx.stage }}
            create: true
            path: \${{ vars.outPath }}
      - uses: git-clear
        config:
          path: \${{ vars.outPath }}
      # - uses: kustomize-set-image
      #   as: update-image
      #   config:
      #     path: \${{ vars.srcPath }}/base
      #     images:
      #     - image: \${{ vars.imageRepo }}
            # tag: \${{ imageFrom(vars.imageRepo).Tag }}
      - uses: kustomize-build
        config:
          path: \${{ vars.srcPath }}/stages/\${{ ctx.stage }}
          outPath: \${{ vars.outPath }}/manifests.yaml
      - uses: git-commit
        as: commit
        config:
          path: \${{ vars.outPath }}
          messageFromSteps:
          - update-image
      - uses: git-push
        config:
          path: \${{ vars.outPath }}
      - uses: argocd-update
        config:
          apps:
          - name: kargo-demo-\${{ ctx.stage }}
            sources:
            - repoURL: \${{ vars.gitopsRepo }}
              desiredRevision: \${{ outputs.commit.commit }}
