apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kargo

resources:
  # - https://raw.githubusercontent.com/argoproj/argo-cd/v2.13.0/manifests/ha/install.yaml
  # - rbac.yaml
  # - app.yaml
  - namespace.yaml

images:
  - name: ghcr.io/akuity/kargo
    newName: 833935676990.dkr.ecr.eu-west-1.amazonaws.com/github/akuity/kargo

helmCharts:
- name: kargo
  repo: oci://ghcr.io/akuity/kargo-charts
  version: 1.1.3
  namespace: kargo
  valuesFile: values.yaml