apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crossplane-system

resources:
- ../../base
- providers.yaml

helmGlobals:
  chartHome: helm

helmCharts:
- name: crossplane
  repo: https://charts.crossplane.io/stable
  version: v1.20.0
  releaseName: crossplane
  namespace: crossplane-system
  includeCRDs: true
