apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-aws-pod-id-drc
  namespace: crossplane-system
spec:
  serviceAccountTemplate:
    metadata:
      name: provider-aws-s3
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-s3
  namespace: crossplane-system
spec:
  package: xpkg.crossplane.io/crossplane-contrib/provider-aws-s3:v1.23.0
  runtimeConfigRef:
    name: provider-aws-pod-id-drc
---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
    name: provider-aws-s3
    namespace: crossplane-system
spec:
    credentials:
        source: PodIdentity